// Generated by LiveScript 1.4.0
(function(){
  module.exports = {
    sites: [
      {
        host: 'www.deezer.com',
        parameters: ['id', 'type']
      }, {
        host: 'open.spotify.com',
        parameters: ['uri']
      }, {
        host: 'w.soundcloud.com',
        parameters: ['url']
      }, {
        host: 'api.mixcloud.com',
        parameters: []
      }
    ]
  };
}).call(this);
